version: '3.4'

services:
  drivefoldercsv:
    image: drivefoldercsv
    environment:
      DEFAULT_URL: ${DEFAULT_URL}
      OUTPUT_URL: ${OUTPUT_URL}
      SCOPES: ${SCOPES}
    build:
      context: .
      dockerfile: ./Dockerfile
